language: php

jobs:
  include:
  - name: PHPCS
    php: 7.4
    before_script: composer require squizlabs/php_codesniffer=3.*
    script: vendor/bin/phpcs --standard=PSR12 src tests

  - php: 5.3
    dist: precise
  - php: 5.4
    dist: trusty
  - php: 5.5
    dist: trusty
  - php: 5.6
  - php: 7.0
  - php: 7.1

  # this is also used for coverage
  - php: 7.2
    before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    after_script:
    - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT

install: composer install --no-interaction

script: vendor/bin/phpunit --configuration .phpunit.xml
